/**
 * Master Data Wilayah Indonesia (38 Provinsi dan Kabupaten / Kota)
 * Digunakan untuk cascading dropdown alamat KTP dan domisili karyawan.
 */

export interface ProvinceRegion {
  name: string;
  cities: string[];
}

export const INDONESIA_PROVINCES: ProvinceRegion[] = [
  {
    name: 'Kalimantan Timur',
    cities: [
      'Kota Samarinda',
      'Kota Balikpapan',
      'Kota Bontang',
      'Kabupaten Kutai Kartanegara',
      'Kabupaten Kutai Barat',
      'Kabupaten Kutai Timur',
      'Kabupaten Berau',
      'Kabupaten Penajam Paser Utara',
      'Kabupaten Paser',
      'Kabupaten Mahakam Ulu',
    ],
  },
  {
    name: 'Kalimantan Selatan',
    cities: [
      'Kota Banjarmasin',
      'Kota Banjarbaru',
      'Kabupaten Tanah Bumbu',
      'Kabupaten Kotabaru',
      'Kabupaten Banjar',
      'Kabupaten Tapin',
      'Kabupaten Hulu Sungai Selatan',
      'Kabupaten Hulu Sungai Tengah',
      'Kabupaten Hulu Sungai Utara',
      'Kabupaten Tabalong',
      'Kabupaten Tanah Laut',
      'Kabupaten Barito Kuala',
      'Kabupaten Balangan',
    ],
  },
  {
    name: 'Kalimantan Tengah',
    cities: [
      'Kota Palangka Raya',
      'Kabupaten Barito Utara',
      'Kabupaten Barito Selatan',
      'Kabupaten Barito Timur',
      'Kabupaten Murung Raya',
      'Kabupaten Kapuas',
      'Kabupaten Gunung Mas',
      'Kabupaten Pulang Pisau',
      'Kabupaten Kotawaringin Timur',
      'Kabupaten Kotawaringin Barat',
      'Kabupaten Katingan',
      'Kabupaten Seruyan',
      'Kabupaten Sukamara',
      'Kabupaten Lamandau',
    ],
  },
  {
    name: 'Kalimantan Barat',
    cities: [
      'Kota Pontianak',
      'Kota Singkawang',
      'Kabupaten Ketapang',
      'Kabupaten Sanggau',
      'Kabupaten Sambas',
      'Kabupaten Sintang',
      'Kabupaten Kapuas Hulu',
      'Kabupaten Bengkayang',
      'Kabupaten Landak',
      'Kabupaten Sekadau',
      'Kabupaten Melawi',
      'Kabupaten Kayong Utara',
      'Kabupaten Kubu Raya',
    ],
  },
  {
    name: 'Kalimantan Utara',
    cities: [
      'Kota Tarakan',
      'Kabupaten Bulungan',
      'Kabupaten Malinau',
      'Kabupaten Nunukan',
      'Kabupaten Tana Tidung',
    ],
  },
  {
    name: 'DKI Jakarta',
    cities: [
      'Kota Jakarta Pusat',
      'Kota Jakarta Selatan',
      'Kota Jakarta Barat',
      'Kota Jakarta Timur',
      'Kota Jakarta Utara',
      'Kabupaten Kepulauan Seribu',
    ],
  },
  {
    name: 'Jawa Barat',
    cities: [
      'Kota Bandung',
      'Kota Bekasi',
      'Kota Bogor',
      'Kota Depok',
      'Kota Cimahi',
      'Kota Cirebon',
      'Kota Sukabumi',
      'Kota Tasikmalaya',
      'Kota Banjar',
      'Kabupaten Bandung',
      'Kabupaten Bandung Barat',
      'Kabupaten Bekasi',
      'Kabupaten Bogor',
      'Kabupaten Ciamis',
      'Kabupaten Cianjur',
      'Kabupaten Cirebon',
      'Kabupaten Garut',
      'Kabupaten Indramayu',
      'Kabupaten Karawang',
      'Kabupaten Kuningan',
      'Kabupaten Majalengka',
      'Kabupaten Pangandaran',
      'Kabupaten Purwakarta',
      'Kabupaten Subang',
      'Kabupaten Sukabumi',
      'Kabupaten Sumedang',
      'Kabupaten Tasikmalaya',
    ],
  },
  {
    name: 'Jawa Timur',
    cities: [
      'Kota Surabaya',
      'Kota Malang',
      'Kota Batu',
      'Kota Sidoarjo',
      'Kota Kediri',
      'Kota Madiun',
      'Kota Blitar',
      'Kota Mojokerto',
      'Kota Pasuruan',
      'Kota Probolinggo',
      'Kabupaten Banyuwangi',
      'Kabupaten Bojonegoro',
      'Kabupaten Gresik',
      'Kabupaten Jember',
      'Kabupaten Jombang',
      'Kabupaten Lamongan',
      'Kabupaten Lumajang',
      'Kabupaten Madiun',
      'Kabupaten Magetan',
      'Kabupaten Malang',
      'Kabupaten Mojokerto',
      'Kabupaten Nganjuk',
      'Kabupaten Ngawi',
      'Kabupaten Pacitan',
      'Kabupaten Pamekasan',
      'Kabupaten Pasuruan',
      'Kabupaten Ponorogo',
      'Kabupaten Probolinggo',
      'Kabupaten Sampang',
      'Kabupaten Sidoarjo',
      'Kabupaten Situbondo',
      'Kabupaten Sumenep',
      'Kabupaten Trenggalek',
      'Kabupaten Tuban',
      'Kabupaten Tulungagung',
    ],
  },
  {
    name: 'Jawa Tengah',
    cities: [
      'Kota Semarang',
      'Kota Surakarta (Solo)',
      'Kota Magelang',
      'Kota Salatiga',
      'Kota Pekalongan',
      'Kota Tegal',
      'Kabupaten Banyumas',
      'Kabupaten Batang',
      'Kabupaten Blora',
      'Kabupaten Boyolali',
      'Kabupaten Brebes',
      'Kabupaten Cilacap',
      'Kabupaten Demak',
      'Kabupaten Grobogan',
      'Kabupaten Jepara',
      'Kabupaten Karanganyar',
      'Kabupaten Kebumen',
      'Kabupaten Kendal',
      'Kabupaten Klaten',
      'Kabupaten Kudus',
      'Kabupaten Magelang',
      'Kabupaten Pati',
      'Kabupaten Pekalongan',
      'Kabupaten Pemalang',
      'Kabupaten Purbalingga',
      'Kabupaten Purworejo',
      'Kabupaten Rembang',
      'Kabupaten Semarang',
      'Kabupaten Sragen',
      'Kabupaten Sukoharjo',
      'Kabupaten Tegal',
      'Kabupaten Temanggung',
      'Kabupaten Wonogiri',
      'Kabupaten Wonosobo',
    ],
  },
  {
    name: 'Banten',
    cities: [
      'Kota Tangerang',
      'Kota Tangerang Selatan',
      'Kota Cilegon',
      'Kota Serang',
      'Kabupaten Tangerang',
      'Kabupaten Serang',
      'Kabupaten Pandeglang',
      'Kabupaten Lebak',
    ],
  },
  {
    name: 'D.I. Yogyakarta',
    cities: [
      'Kota Yogyakarta',
      'Kabupaten Sleman',
      'Kabupaten Bantul',
      'Kabupaten Kulon Progo',
      'Kabupaten Gunungkidul',
    ],
  },
  {
    name: 'Sumatera Selatan',
    cities: [
      'Kota Palembang',
      'Kota Prabumulih',
      'Kota Lubuklinggau',
      'Kota Pagar Alam',
      'Kabupaten Muara Enim',
      'Kabupaten Lahat',
      'Kabupaten Banyuasin',
      'Kabupaten Musi Banyuasin',
      'Kabupaten Musi Rawas',
      'Kabupaten Musi Rawas Utara',
      'Kabupaten Ogan Ilir',
      'Kabupaten Ogan Komering Ilir',
      'Kabupaten Ogan Komering Ulu',
      'Kabupaten Ogan Komering Ulu Selatan',
      'Kabupaten Ogan Komering Ulu Timur',
      'Kabupaten Penukal Abab Lematang Ilir',
      'Kabupaten Empat Lawang',
    ],
  },
  {
    name: 'Riau',
    cities: [
      'Kota Pekanbaru',
      'Kota Dumai',
      'Kabupaten Bengkalis',
      'Kabupaten Indragiri Hilir',
      'Kabupaten Indragiri Hulu',
      'Kabupaten Kampar',
      'Kabupaten Kepulauan Meranti',
      'Kabupaten Kuantan Singingi',
      'Kabupaten Pelalawan',
      'Kabupaten Rokan Hilir',
      'Kabupaten Rokan Hulu',
      'Kabupaten Siak',
    ],
  },
  {
    name: 'Kepulauan Riau',
    cities: [
      'Kota Batam',
      'Kota Tanjungpinang',
      'Kabupaten Bintan',
      'Kabupaten Karimun',
      'Kabupaten Kepulauan Anambas',
      'Kabupaten Lingga',
      'Kabupaten Natuna',
    ],
  },
  {
    name: 'Sumatera Utara',
    cities: [
      'Kota Medan',
      'Kota Binjai',
      'Kota Padangsidimpuan',
      'Kota Pematangsiantar',
      'Kota Sibolga',
      'Kota Tanjungbalai',
      'Kota Tebing Tinggi',
      'Kota Gunungsitoli',
      'Kabupaten Asahan',
      'Kabupaten Deli Serdang',
      'Kabupaten Karo',
      'Kabupaten Labuhanbatu',
      'Kabupaten Langkat',
      'Kabupaten Mandailing Natal',
      'Kabupaten Nias',
      'Kabupaten Simalungun',
      'Kabupaten Tapanuli Selatan',
      'Kabupaten Tapanuli Tengah',
      'Kabupaten Tapanuli Utara',
      'Kabupaten Toba',
    ],
  },
  {
    name: 'Sumatera Barat',
    cities: [
      'Kota Padang',
      'Kota Bukittinggi',
      'Kota Padang Panjang',
      'Kota Pariaman',
      'Kota Payakumbuh',
      'Kota Sawahlunto',
      'Kota Solok',
      'Kabupaten Agam',
      'Kabupaten Lima Puluh Kota',
      'Kabupaten Padang Pariaman',
      'Kabupaten Pasaman',
      'Kabupaten Pasaman Barat',
      'Kabupaten Pesisir Selatan',
      'Kabupaten Sijunjung',
      'Kabupaten Solok',
      'Kabupaten Solok Selatan',
      'Kabupaten Tanah Datar',
    ],
  },
  {
    name: 'Lampung',
    cities: [
      'Kota Bandar Lampung',
      'Kota Metro',
      'Kabupaten Lampung Barat',
      'Kabupaten Lampung Selatan',
      'Kabupaten Lampung Tengah',
      'Kabupaten Lampung Timur',
      'Kabupaten Lampung Utara',
      'Kabupaten Mesuji',
      'Kabupaten Pesawaran',
      'Kabupaten Pesisir Barat',
      'Kabupaten Pringsewu',
      'Kabupaten Tanggamus',
      'Kabupaten Tulang Bawang',
      'Kabupaten Tulang Bawang Barat',
      'Kabupaten Way Kanan',
    ],
  },
  {
    name: 'Jambi',
    cities: [
      'Kota Jambi',
      'Kota Sungai Penuh',
      'Kabupaten Batanghari',
      'Kabupaten Bungo',
      'Kabupaten Kerinci',
      'Kabupaten Merangin',
      'Kabupaten Muaro Jambi',
      'Kabupaten Sarolangun',
      'Kabupaten Tanjung Jabung Barat',
      'Kabupaten Tanjung Jabung Timur',
      'Kabupaten Tebo',
    ],
  },
  {
    name: 'Aceh',
    cities: [
      'Kota Banda Aceh',
      'Kota Langsa',
      'Kota Lhokseumawe',
      'Kota Sabang',
      'Kota Subulussalam',
      'Kabupaten Aceh Barat',
      'Kabupaten Aceh Besar',
      'Kabupaten Aceh Selatan',
      'Kabupaten Aceh Tengah',
      'Kabupaten Aceh Timur',
      'Kabupaten Aceh Utara',
      'Kabupaten Bireuen',
      'Kabupaten Pidie',
    ],
  },
  {
    name: 'Bengkulu',
    cities: [
      'Kota Bengkulu',
      'Kabupaten Bengkulu Selatan',
      'Kabupaten Bengkulu Tengah',
      'Kabupaten Bengkulu Utara',
      'Kabupaten Kaur',
      'Kabupaten Kepahiang',
      'Kabupaten Lebong',
      'Kabupaten Mukomuko',
      'Kabupaten Rejang Lebong',
      'Kabupaten Seluma',
    ],
  },
  {
    name: 'Kepulauan Bangka Belitung',
    cities: [
      'Kota Pangkalpinang',
      'Kabupaten Bangka',
      'Kabupaten Bangka Barat',
      'Kabupaten Bangka Selatan',
      'Kabupaten Bangka Tengah',
      'Kabupaten Belitung',
      'Kabupaten Belitung Timur',
    ],
  },
  {
    name: 'Bali',
    cities: [
      'Kota Denpasar',
      'Kabupaten Badung',
      'Kabupaten Bangli',
      'Kabupaten Buleleng',
      'Kabupaten Gianyar',
      'Kabupaten Jembrana',
      'Kabupaten Karangasem',
      'Kabupaten Klungkung',
      'Kabupaten Tabanan',
    ],
  },
  {
    name: 'Nusa Tenggara Barat',
    cities: [
      'Kota Mataram',
      'Kota Bima',
      'Kabupaten Bima',
      'Kabupaten Dompu',
      'Kabupaten Lombok Barat',
      'Kabupaten Lombok Tengah',
      'Kabupaten Lombok Timur',
      'Kabupaten Lombok Utara',
      'Kabupaten Sumbawa',
      'Kabupaten Sumbawa Barat',
    ],
  },
  {
    name: 'Nusa Tenggara Timur',
    cities: [
      'Kota Kupang',
      'Kabupaten Alor',
      'Kabupaten Belu',
      'Kabupaten Ende',
      'Kabupaten Flores Timur',
      'Kabupaten Kupang',
      'Kabupaten Lembata',
      'Kabupaten Manggarai',
      'Kabupaten Manggarai Barat',
      'Kabupaten Manggarai Timur',
      'Kabupaten Nagekeo',
      'Kabupaten Ngada',
      'Kabupaten Rote Ndao',
      'Kabupaten Sabu Raijua',
      'Kabupaten Sikka',
      'Kabupaten Sumba Barat',
      'Kabupaten Sumba Barat Daya',
      'Kabupaten Sumba Tengah',
      'Kabupaten Sumba Timur',
      'Kabupaten Timor Tengah Selatan',
      'Kabupaten Timor Tengah Utara',
    ],
  },
  {
    name: 'Sulawesi Selatan',
    cities: [
      'Kota Makassar',
      'Kota Palopo',
      'Kota Parepare',
      'Kabupaten Bantaeng',
      'Kabupaten Barru',
      'Kabupaten Bone',
      'Kabupaten Bulukumba',
      'Kabupaten Enrekang',
      'Kabupaten Gowa',
      'Kabupaten Jeneponto',
      'Kabupaten Kepulauan Selayar',
      'Kabupaten Luwu',
      'Kabupaten Luwu Timur',
      'Kabupaten Luwu Utara',
      'Kabupaten Maros',
      'Kabupaten Pangkajene dan Kepulauan',
      'Kabupaten Pinrang',
      'Kabupaten Sidenreng Rappang',
      'Kabupaten Sinjai',
      'Kabupaten Soppeng',
      'Kabupaten Takalar',
      'Kabupaten Tana Toraja',
      'Kabupaten Toraja Utara',
      'Kabupaten Wajo',
    ],
  },
  {
    name: 'Sulawesi Tengah',
    cities: [
      'Kota Palu',
      'Kabupaten Banggai',
      'Kabupaten Banggai Kepulauan',
      'Kabupaten Banggai Laut',
      'Kabupaten Buol',
      'Kabupaten Donggala',
      'Kabupaten Morowali',
      'Kabupaten Morowali Utara',
      'Kabupaten Parigi Moutong',
      'Kabupaten Poso',
      'Kabupaten Sigi',
      'Kabupaten Tojo Una-Una',
      'Kabupaten Tolitoli',
    ],
  },
  {
    name: 'Sulawesi Tenggara',
    cities: [
      'Kota Kendari',
      'Kota Baubau',
      'Kabupaten Bombana',
      'Kabupaten Buton',
      'Kabupaten Buton Selatan',
      'Kabupaten Buton Tengah',
      'Kabupaten Buton Utara',
      'Kabupaten Kolaka',
      'Kabupaten Kolaka Timur',
      'Kabupaten Kolaka Utara',
      'Kabupaten Konawe',
      'Kabupaten Konawe Kepulauan',
      'Kabupaten Konawe Selatan',
      'Kabupaten Konawe Utara',
      'Kabupaten Muna',
      'Kabupaten Muna Barat',
      'Kabupaten Wakatobi',
    ],
  },
  {
    name: 'Sulawesi Utara',
    cities: [
      'Kota Manado',
      'Kota Bitung',
      'Kota Kotamobagu',
      'Kota Tomohon',
      'Kabupaten Bolaang Mongondow',
      'Kabupaten Bolaang Mongondow Selatan',
      'Kabupaten Bolaang Mongondow Timur',
      'Kabupaten Bolaang Mongondow Utara',
      'Kabupaten Kepulauan Sangihe',
      'Kabupaten Kepulauan Siau Tagulandang Biaro',
      'Kabupaten Kepulauan Talaud',
      'Kabupaten Minahasa',
      'Kabupaten Minahasa Selatan',
      'Kabupaten Minahasa Tenggara',
      'Kabupaten Minahasa Utara',
    ],
  },
  {
    name: 'Sulawesi Barat',
    cities: [
      'Kabupaten Majene',
      'Kabupaten Mamasa',
      'Kabupaten Mamuju',
      'Kabupaten Mamuju Tengah',
      'Kabupaten Pasangkayu',
      'Kabupaten Polewali Mandar',
    ],
  },
  {
    name: 'Gorontalo',
    cities: [
      'Kota Gorontalo',
      'Kabupaten Boalemo',
      'Kabupaten Bone Bolango',
      'Kabupaten Gorontalo',
      'Kabupaten Gorontalo Utara',
      'Kabupaten Pohuwato',
    ],
  },
  {
    name: 'Maluku',
    cities: [
      'Kota Ambon',
      'Kota Tual',
      'Kabupaten Buru',
      'Kabupaten Buru Selatan',
      'Kabupaten Kepulauan Aru',
      'Kabupaten Kepulauan Tanimbar',
      'Kabupaten Maluku Barat Daya',
      'Kabupaten Maluku Tengah',
      'Kabupaten Maluku Tenggara',
      'Kabupaten Seram Bagian Barat',
      'Kabupaten Seram Bagian Timur',
    ],
  },
  {
    name: 'Maluku Utara',
    cities: [
      'Kota Ternate',
      'Kota Tidore Kepulauan',
      'Kabupaten Halmahera Barat',
      'Kabupaten Halmahera Tengah',
      'Kabupaten Halmahera Timur',
      'Kabupaten Halmahera Selatan',
      'Kabupaten Halmahera Utara',
      'Kabupaten Kepulauan Sula',
      'Kabupaten Pulau Morotai',
      'Kabupaten Pulau Taliabu',
    ],
  },
  {
    name: 'Papua',
    cities: [
      'Kota Jayapura',
      'Kabupaten Jayapura',
      'Kabupaten Keerom',
      'Kabupaten Mamberamo Raya',
      'Kabupaten Sarmi',
      'Kabupaten Biak Numfor',
      'Kabupaten Supiori',
      'Kabupaten Kepulauan Yapen',
      'Kabupaten Waropen',
    ],
  },
  {
    name: 'Papua Barat',
    cities: [
      'Kabupaten Fakfak',
      'Kabupaten Kaimana',
      'Kabupaten Manokwari',
      'Kabupaten Manokwari Selatan',
      'Kabupaten Pegunungan Arfak',
      'Kabupaten Teluk Bintuni',
      'Kabupaten Teluk Wondama',
    ],
  },
  {
    name: 'Papua Barat Daya',
    cities: [
      'Kota Sorong',
      'Kabupaten Maybrat',
      'Kabupaten Raja Ampat',
      'Kabupaten Sorong',
      'Kabupaten Sorong Selatan',
      'Kabupaten Tambrauw',
    ],
  },
  {
    name: 'Papua Selatan',
    cities: [
      'Kabupaten Asmat',
      'Kabupaten Boven Digoel',
      'Kabupaten Mappi',
      'Kabupaten Merauke',
    ],
  },
  {
    name: 'Papua Tengah',
    cities: [
      'Kabupaten Deiyai',
      'Kabupaten Dogiyai',
      'Kabupaten Intan Jaya',
      'Kabupaten Mimika',
      'Kabupaten Nabire',
      'Kabupaten Paniai',
      'Kabupaten Puncak',
      'Kabupaten Puncak Jaya',
    ],
  },
  {
    name: 'Papua Pegunungan',
    cities: [
      'Kabupaten Jayawijaya',
      'Kabupaten Lanny Jaya',
      'Kabupaten Mamberamo Tengah',
      'Kabupaten Nduga',
      'Kabupaten Pegunungan Bintang',
      'Kabupaten Tolikara',
      'Kabupaten Yahukimo',
      'Kabupaten Yalimo',
    ],
  },
];

export const getCitiesByProvince = (provinceName: string): string[] => {
  const found = INDONESIA_PROVINCES.find(
    (p) => p.name.toLowerCase() === provinceName?.trim().toLowerCase()
  );
  return found ? found.cities : [];
};

export const INDONESIA_DISTRICTS: Record<string, string[]> = {
  // KALIMANTAN TIMUR
  'Kota Samarinda': [
    'Samarinda Kota',
    'Samarinda Ulu',
    'Samarinda Ilir',
    'Samarinda Seberang',
    'Sungai Kunjang',
    'Palaran',
    'Sungai Pinang',
    'Sambutan',
    'Loa Janan Ilir',
    'Samarinda Utara',
  ],
  'Kota Balikpapan': [
    'Balikpapan Kota',
    'Balikpapan Selatan',
    'Balikpapan Tengah',
    'Balikpapan Utara',
    'Balikpapan Barat',
    'Balikpapan Timur',
  ],
  'Kota Bontang': ['Bontang Barat', 'Bontang Selatan', 'Bontang Utara'],
  'Kabupaten Kutai Kartanegara': [
    'Tenggarong',
    'Tenggarong Seberang',
    'Loa Janan',
    'Loa Kulu',
    'Muara Jawa',
    'Samboja',
    'Samboja Barat',
    'Sanga-Sanga',
    'Anggana',
    'Muara Badak',
    'Marang Kayu',
    'Sebulu',
    'Kota Bangun',
    'Kota Bangun Darat',
    'Muara Kaman',
    'Kenohan',
    'Kembang Janggut',
    'Tabang',
    'Muara Muntai',
  ],
  'Kabupaten Kutai Barat': [
    'Barong Tongkok',
    'Melak',
    'Linggang Bigung',
    'Damai',
    'Muara Pahu',
    'Muara Lawa',
    'Jempang',
    'Bongan',
    'Siluq Ngurai',
    'Bentian Besar',
    'Penyinggahan',
    'Sekolaq Darat',
    'Nyuatan',
    'Mook Manaar Bulatn',
    'Tering',
    'Long Iram',
  ],
  'Kabupaten Kutai Timur': [
    'Sangatta Utara',
    'Sangatta Selatan',
    'Bengalon',
    'Rantau Pulung',
    'Teluk Pandan',
    'Muara Wahau',
    'Kongbeng',
    'Telen',
    'Muara Ancalong',
    'Muara Bengkal',
    'Long Mesangat',
    'Busang',
    'Batu Ampar',
    'Sandaran',
    'Sangkulirang',
    'Kaliorang',
    'Kaubun',
    'Karangan',
  ],
  'Kabupaten Berau': [
    'Tanjung Redeb',
    'Gunung Tabur',
    'Sambaliung',
    'Teluk Bayur',
    'Pulau Derawan',
    'Maratua',
    'Biduk-Biduk',
    'Batu Putih',
    'Talisayan',
    'Biatan',
    'Tabalar',
    'Segah',
    'Kelay',
  ],
  'Kabupaten Penajam Paser Utara': ['Penajam', 'Waru', 'Babulu', 'Sepaku'],
  'Kabupaten Paser': [
    'Tanah Grogot',
    'Kuaro',
    'Long Ikis',
    'Long Kali',
    'Pasir Belengkong',
    'Muara Samu',
    'Batu Sopang',
    'Muara Komam',
    'Tanjung Harapan',
    'Batu Engau',
  ],
  'Kabupaten Mahakam Ulu': ['Long Bagun', 'Long Hubung', 'Laham', 'Long Apari', 'Long Pahangai'],

  // KALIMANTAN SELATAN
  'Kota Banjarmasin': ['Banjarmasin Barat', 'Banjarmasin Selatan', 'Banjarmasin Tengah', 'Banjarmasin Timur', 'Banjarmasin Utara'],
  'Kota Banjarbaru': ['Banjarbaru Selatan', 'Banjarbaru Utara', 'Cempaka', 'Landasan Ulin', 'Liang Anggang'],
  'Kabupaten Tanah Bumbu': [
    'Batulicin',
    'Simpang Empat',
    'Kusan Hilir',
    'Kusan Hulu',
    'Kusan Tengah',
    'Sungai Loban',
    'Satui',
    'Angsana',
    'Karang Bintang',
    'Mantewe',
    'Kuranji',
    'Teluk Kepayang',
  ],
  'Kabupaten Kotabaru': [
    'Pulau Laut Utara',
    'Pulau Laut Sigam',
    'Pulau Laut Timur',
    'Pulau Laut Tengah',
    'Pulau Laut Barat',
    'Pulau Laut Selatan',
    'Kelumpang Hilir',
    'Kelumpang Hulu',
    'Kelumpang Selatan',
    'Kelumpang Tengah',
    'Kelumpang Barat',
    'Kelumpang Utara',
    'Pamukan Barat',
    'Pamukan Selatan',
    'Pamukan Utara',
    'Sungai Durian',
    'Sampanahan',
  ],
  'Kabupaten Banjar': ['Martapura', 'Martapura Barat', 'Martapura Timur', 'Karang Intan', 'Astambul', 'Simpang Empat', 'Pengaron', 'Mataraman', 'Gambut', 'Kertak Hanyar', 'Aluh-Aluh'],
  'Kabupaten Tabalong': ['Tanjung', 'Murung Pudak', 'Tanta', 'Kelua', 'Haruai', 'Bintang Ara', 'Upau', 'Muara Uya', 'Jaro', 'Pugaan', 'Banua Lawas', 'Muara Harus'],
  'Kabupaten Tapin': ['Tapin Utara', 'Tapin Tengah', 'Tapin Selatan', 'Bakarangan', 'Lokpaikat', 'Binuang', 'Hatungun', 'Salam Babaris', 'Piani', 'Candi Laras Utara', 'Candi Laras Selatan'],
  'Kabupaten Tanah Laut': ['Pelaihari', 'Bati-Bati', 'Tambang Ulang', 'Kurau', 'Bumi Makmur', 'Takisung', 'Panyipatan', 'Kintap', 'Jorong', 'Batu Ampar', 'Bajuin'],
  'Kabupaten Barito Kuala': ['Marabahan', 'Alalak', 'Mandastana', 'Rantau Badauh', 'Belawang', 'Cerbon', 'Bakumpai', 'Kuripan', 'Tabukan', 'Barambai', 'Wanaraya', 'Anjir Pasar', 'Anjir Muara', 'Tamban', 'Mekarsari', 'Tabunganen'],
  'Kabupaten Balangan': ['Paringin', 'Paringin Selatan', 'Batu Mandi', 'Lampihong', 'Awayan', 'Juai', 'Tebing Tinggi', 'Halong'],
  'Kabupaten Hulu Sungai Selatan': ['Kandangan', 'Sungai Raya', 'Simpur', 'Daha Selatan', 'Daha Utara', 'Daha Barat', 'Angkinang', 'Telaga Langsat', 'Padang Batung', 'Loksado'],
  'Kabupaten Hulu Sungai Tengah': ['Barabai', 'Batu Benawa', 'Hantakan', 'Batang Alai Selatan', 'Batang Alai Utara', 'Batang Alai Timur', 'Labuan Amas Selatan', 'Labuan Amas Utara', 'Pandawan', 'Haruyan', 'Limpasu'],
  'Kabupaten Hulu Sungai Utara': ['Amuntai Tengah', 'Amuntai Utara', 'Amuntai Selatan', 'Banjang', 'Danau Panggang', 'Babirik', 'Sungai Pandan', 'Sungai Tabukan', 'Paminggir', 'Haur Gading'],

  // KALIMANTAN TENGAH
  'Kota Palangka Raya': ['Pahandut', 'Jekan Raya', 'Bukit Batu', 'Sebangau', 'Rakumpit'],
  'Kabupaten Barito Utara': ['Muara Teweh', 'Teweh Tengah', 'Teweh Baru', 'Teweh Selatan', 'Teweh Timur', 'Lahei', 'Lahei Barat', 'Montallat', 'Gunung Timang', 'Gunung Purei'],
  'Kabupaten Murung Raya': ['Murung', 'Tanah Siang', 'Tanah Siang Selatan', 'Laung Tuhup', 'Permata Intan', 'Sumber Barito', 'Sungai Babuat', 'Barito Tuhup Raya', 'Seribu Riam', 'Uut Murung'],
  'Kabupaten Barito Timur': ['Tamiang Layang', 'Dusun Timur', 'Dusun Tengah', 'Pematang Karau', 'Awang', 'Patangkep Tutui', 'Benua Lima', 'Paju Epat', 'Raren Batuah', 'Pakuan', 'Karusen Janang'],
  'Kabupaten Barito Selatan': ['Buntok', 'Dusun Selatan', 'Dusun Utara', 'Dusun Hilir', 'Karau Kuala', 'Jenamas', 'Gunung Bintang Awai'],
  'Kabupaten Kotawaringin Timur': ['Sampit', 'Mentawa Baru Ketapang', 'Baamang', 'Seranau', 'Kotabesi', 'Cempaga', 'Cempaga Hulu', 'Parenggean', 'Mentaya Hulu', 'Mentaya Hilir Utara', 'Mentaya Hilir Selatan', 'Pulau Hanaut', 'Antang Kalang', 'Telawang', 'Bukit Santuai', 'Tualan Hulu', 'Teluk Sampit'],
  'Kabupaten Kotawaringin Barat': ['Pangkalan Bun', 'Arut Selatan', 'Arut Utara', 'Kumai', 'Kotawaringin Lama', 'Pangkalan Lada', 'Pangkalan Banteng'],
  'Kabupaten Kapuas': ['Selat', 'Kapuas Barat', 'Kapuas Murung', 'Kapuas Timur', 'Kapuas Tengah', 'Kapuas Hulu', 'Kapuas Kuala', 'Basarang', 'Mantangai', 'Timpah', 'Pasak Talawang', 'Tamban Catur', 'Dadahup', 'Bataguh', 'Mandau Talawang'],
  'Kabupaten Seruyan': ['Kuala Pembuang', 'Seruyan Hilir', 'Seruyan Hilir Timur', 'Seruyan Tengah', 'Seruyan Hulu', 'Seruyan Raya', 'Danau Sembuluh', 'Danau Seluluk', 'Batu Ampar', 'Suling Tambun'],
  'Kabupaten Katingan': ['Kasongan', 'Katingan Hilir', 'Katingan Tengah', 'Katingan Hulu', 'Tewang Sangalang Garing', 'Pulau Malan', 'Kamipang', 'Mendawai', 'Katingan Kuala', 'Marikit', 'Sanaman Mantikei', 'Petak Malai', 'Bukit Raya'],
  'Kabupaten Gunung Mas': ['Kuala Kurun', 'Kurun', 'Tewah', 'Kahayan Hulu Utara', 'Rungan', 'Rungan Barat', 'Rungan Hulu', 'Manuhing', 'Manuhing Raya', 'Sepang', 'Mihing Raya', 'Damang Batu'],
  'Kabupaten Pulang Pisau': ['Kahayan Hilir', 'Kahayan Tengah', 'Kahayan Kuala', 'Maliku', 'Pandih Batu', 'Banama Tingang', 'Sebangau Kuala', 'Jabiren Raya'],
  'Kabupaten Sukamara': ['Sukamara', 'Jelai', 'Pantai Lunci', 'Balai Riam', 'Permata Kecubung'],
  'Kabupaten Lamandau': ['Nanga Bulik', 'Bulik', 'Bulik Timur', 'Sematu Jaya', 'Menthobi Raya', 'Lamandau', 'Belantikan Raya', 'Delang', 'Batangkawa'],

  // KALIMANTAN BARAT
  'Kota Pontianak': ['Pontianak Kota', 'Pontianak Barat', 'Pontianak Selatan', 'Pontianak Tenggara', 'Pontianak Timur', 'Pontianak Utara'],
  'Kota Singkawang': ['Singkawang Barat', 'Singkawang Selatan', 'Singkawang Tengah', 'Singkawang Timur', 'Singkawang Utara'],
  'Kabupaten Ketapang': ['Delta Pawan', 'Benua Kayong', 'Muara Pawan', 'Matan Hilir Utara', 'Matan Hilir Selatan', 'Kendawangan', 'Manis Mata', 'Marau', 'Singkup', 'Air Upas', 'Sandai', 'Nanga Tayap', 'Sungai Laur', 'Simpang Dua', 'Simpang Hulu', 'Jelai Hulu', 'Tumbang Titi', 'Pemahan', 'Sungai Melayu Rayak', 'Hulu Sungai'],
  'Kabupaten Kubu Raya': ['Sungai Raya', 'Kuala Mandor B', 'Sungai Ambawang', 'Terentang', 'Batu Ampar', 'Kubuk', 'Rasau Jaya', 'Teluk Pakedai', 'Sungai Kakap'],
  'Kabupaten Sanggau': ['Kapuas', 'Mukok', 'Noyan', 'Bonti', 'Parindu', 'Tayan Hilir', 'Tayan Hulu', 'Balai', 'Toba', 'Meliau', 'Sekayam', 'Kembayan', 'Beduai', 'Entikong', 'Jangkang'],
  'Kabupaten Sambas': ['Sambas', 'Sebawi', 'Teluk Keramat', 'Tangaran', 'Galing', 'Paloh', 'Teluk Keramat', 'Jawai', 'Jawai Selatan', 'Pemangkat', 'Semparuk', 'Salatiga', 'Selakau', 'Selakau Timur', 'Tebas', 'Tekarang', 'Subah', 'Sajingan Besar', 'Sebalau'],
  'Kabupaten Sintang': ['Sintang', 'Kelam Permai', 'Dedai', 'Kayan Hilir', 'Kayan Hulu', 'Sepauk', 'Tempunak', 'Ketungau Hilir', 'Ketungau Tengah', 'Ketungau Hulu', 'Sungai Tebelian', 'Binjai Hulu', 'Ambalau', 'Serawai'],

  // KALIMANTAN UTARA
  'Kota Tarakan': ['Tarakan Barat', 'Tarakan Tengah', 'Tarakan Timur', 'Tarakan Utara'],
  'Kabupaten Bulungan': ['Tanjung Selor', 'Tanjung Palas', 'Tanjung Palas Barat', 'Tanjung Palas Timur', 'Tanjung Palas Utara', 'Tanjung Palas Tengah', 'Peso', 'Peso Hilir', 'Sekatak', 'Bunyu'],
  'Kabupaten Nunukan': ['Nunukan', 'Nunukan Selatan', 'Sebatik', 'Sebatik Barat', 'Sebatik Timur', 'Sebatik Tengah', 'Sebatik Utara', 'Sembakung', 'Sembakung Atulai', 'Lumbis', 'Krayan', 'Krayan Selatan'],
  'Kabupaten Malinau': ['Malinau Kota', 'Malinau Barat', 'Malinau Utara', 'Malinau Selatan', 'Malinau Selatan Hilir', 'Malinau Selatan Hulu', 'Mentarang', 'Mentarang Hulu', 'Pujungan', 'Kayan Hulu'],
  'Kabupaten Tana Tidung': ['Sesayap', 'Sesayap Hilir', 'Betayau', 'Muruk Rian', 'Tana Lia'],

  // DKI JAKARTA
  'Kota Jakarta Pusat': ['Gambir', 'Tanah Abang', 'Menteng', 'Senen', 'Cempaka Putih', 'Johar Baru', 'Kemayoran', 'Sawah Besar'],
  'Kota Jakarta Selatan': ['Kebayoran Baru', 'Kebayoran Lama', 'Pesanggrahan', 'Cilandak', 'Pasar Minggu', 'Jagakarsa', 'Mampang Prapatan', 'Pancoran', 'Tebet', 'Setiabudi'],
  'Kota Jakarta Barat': ['Cengkareng', 'Grogol Petamburan', 'Taman Sari', 'Tambora', 'Kebon Jeruk', 'Kalideres', 'Palmerah', 'Kembangan'],
  'Kota Jakarta Timur': ['Matraman', 'Pulo Gadung', 'Jatinegara', 'Duren Sawit', 'Kramat Jati', 'Makasar', 'Pasar Rebo', 'Ciracas', 'Cipayung', 'Cakung'],
  'Kota Jakarta Utara': ['Penjaringan', 'Pademangan', 'Tanjung Priok', 'Koja', 'Kelapa Gading', 'Cilincing'],
  'Kabupaten Kepulauan Seribu': ['Kepulauan Seribu Selatan', 'Kepulauan Seribu Utara'],

  // JAWA BARAT
  'Kota Bandung': ['Coblong', 'Sukajadi', 'Andir', 'Cicendo', 'Astanaanyar', 'Bojongloa Kaler', 'Bojongloa Kidul', 'Lengkong', 'Regol', 'Batununggal', 'Kiaracondong', 'Antapani', 'Arcamanik', 'Cibiru', 'Ujungberung', 'Buahbatu', 'Rancasari', 'Gedebage', 'Bandung Wetan', 'Sumur Bandung', 'Cibeunying Kaler', 'Cibeunying Kidul', 'Babakan Ciparay', 'Sukanyar'],
  'Kota Bekasi': ['Bekasi Barat', 'Bekasi Timur', 'Bekasi Utara', 'Bekasi Selatan', 'Rawalumbu', 'Medansatria', 'Bantar Gebang', 'Pondok Gede', 'Jatiasih', 'Jatisampurna', 'Mustikajaya', 'Pondok Melati'],
  'Kota Depok': ['Pancoran Mas', 'Sukmajaya', 'Cimanggis', 'Sawangan', 'Limo', 'Beji', 'Cipayung', 'Cilodong', 'Cinere', 'Tapos', 'Bojongsari'],
  'Kota Bogor': ['Bogor Barat', 'Bogor Selatan', 'Bogor Tengah', 'Bogor Timur', 'Bogor Utara', 'Tanah Sareal'],
  'Kabupaten Bogor': ['Cibinong', 'Cileungsi', 'Gunung Putri', 'Citeureup', 'Babakan Madang', 'Jonggol', 'Parung', 'Ciawi', 'Megamendung', 'Cisarua', 'Ciampea', 'Leuwiliang', 'Tamansari', 'Kemang', 'Bojonggede'],
  'Kabupaten Bekasi': ['Cikarang Pusat', 'Cikarang Barat', 'Cikarang Timur', 'Cikarang Utara', 'Cikarang Selatan', 'Tambun Selatan', 'Tambun Utara', 'Cibitung', 'Setu', 'Serang Baru', 'Babelan', 'Tarumajaya'],
  'Kabupaten Karawang': ['Karawang Barat', 'Karawang Timur', 'Telukjambe Timur', 'Telukjambe Barat', 'Klari', 'Kotabaru', 'Cikampek', 'Rengasdengklok', 'Majalaya', 'Purwasari', 'Jatisari'],

  // BANTEN
  'Kota Tangerang': ['Tangerang', 'Batuceper', 'Benda', 'Cibodas', 'Ciledug', 'Cipondoh', 'Jatiuwung', 'Karang Tengah', 'Karawaci', 'Larangan', 'Neglasari', 'Periuk', 'Pinang'],
  'Kota Tangerang Selatan': ['Serpong', 'Serpong Utara', 'Pondok Aren', 'Ciputat', 'Ciputat Timur', 'Pamulang', 'Setu'],
  'Kabupaten Tangerang': ['Tigaraksa', 'Balaraja', 'Cikupa', 'Curug', 'Kelapa Dua', 'Legok', 'Pasar Kemis', 'Panongan', 'Rajeg', 'Sepatan', 'Teluknaga', 'Kosambi'],
  'Kota Cilegon': ['Cilegon', 'Cibeber', 'Citangkil', 'Ciwandan', 'Gerogol', 'Jombang', 'Pulomerak', 'Purwakarta'],
  'Kota Serang': ['Serang', 'Cipocok Jaya', 'Curug', 'Kasemen', 'Taktakan', 'Walantaka'],

  // JAWA TENGAH & DI YOGYAKARTA
  'Kota Semarang': ['Semarang Tengah', 'Semarang Barat', 'Semarang Timur', 'Semarang Utara', 'Semarang Selatan', 'Candisari', 'Gajahmungkur', 'Gayamsari', 'Genuk', 'Gunungpati', 'Mijen', 'Ngaliyan', 'Pedurungan', 'Tembalang', 'Tugu', 'Banyumanik'],
  'Kota Surakarta': ['Banjarsari', 'Jebres', 'Laweyan', 'Pasar Kliwon', 'Serengan'],
  'Kota Yogyakarta': ['Danurejan', 'Gedongtengen', 'Gondokusuman', 'Gondomanan', 'Jetis', 'Kotagede', 'Kraton', 'Mantrijeron', 'Mergangsan', 'Ngampilan', 'Pakualaman', 'Tegalrejo', 'Umbulharjo', 'Wirobrajan'],
  'Kabupaten Sleman': ['Depok', 'Mlati', 'Gamping', 'Godean', 'Ngaglik', 'Kalasan', 'Berbah', 'Prambanan', 'Sleman', 'Tempel', 'Turi', 'Pakem', 'Cangkringan'],
  'Kabupaten Bantul': ['Bantul', 'Sewon', 'Kasihan', 'Banguntapan', 'Piyungan', 'Pleret', 'Imogiri', 'Dlingo', 'Kretek', 'Sanden', 'Srandakan', 'Pandak', 'Pajangan', 'Sedayu'],

  // JAWA TIMUR
  'Kota Surabaya': ['Tegalsari', 'Simokerto', 'Genteng', 'Bubutan', 'Gubeng', 'Gunung Anyar', 'Sukolilo', 'Tambaksari', 'Mulyorejo', 'Rungkut', 'Tenggilis Mejoyo', 'Wonokromo', 'Sawahan', 'Pegirian', 'Semampir', 'Pabean Cantian', 'Krembangan', 'Kenjeran', 'Bulak', 'Wonocolo', 'Wiyung', 'Karangpilang', 'Jambangan', 'Gayungan', 'Dukuh Pakis', 'Sukomanunggal', 'Tandes', 'Benowo', 'Pakal', 'Asemrowo', 'Sambikerep', 'Lakarsantri'],
  'Kota Malang': ['Klojen', 'Blimbing', 'Kedungkandang', 'Lowokwaru', 'Sukun'],
  'Kabupaten Sidoarjo': ['Sidoarjo', 'Waru', 'Gedangan', 'Buduran', 'Taman', 'Krian', 'Candi', 'Porong', 'Sukodono', 'Sedati', 'Tulangan', 'Wonoayu'],
  'Kabupaten Gresik': ['Gresik', 'Kebomas', 'Manyar', 'Driyorejo', 'Menganti', 'Cerme', 'Benjeng', 'Balongpanggang', 'Bungah', 'Sidayu', 'Ujungpangkah'],

  // SUMATERA & SULAWESI & PAPUA (Pusat Tambang & Bisnis)
  'Kota Medan': ['Medan Kota', 'Medan Baru', 'Medan Barat', 'Medan Timur', 'Medan Helvetia', 'Medan Petisah', 'Medan Sunggal', 'Medan Selayang', 'Medan Tuntungan', 'Medan Johor', 'Medan Denai', 'Medan Amplas', 'Medan Area', 'Medan Deli', 'Medan Labuhan', 'Medan Belawan', 'Medan Marelan'],
  'Kota Palembang': ['Ilir Timur I', 'Ilir Timur II', 'Ilir Barat I', 'Ilir Barat II', 'Sukarami', 'Alang-Alang Lebar', 'Kalidoni', 'Sako', 'Sematang Borang', 'Kemuning', 'Seberang Ulu I', 'Seberang Ulu II', 'Plaju', 'Kertapati', 'Gandus', 'Jakabaring'],
  'Kabupaten Muara Enim': ['Muara Enim', 'Lawang Kidul', 'Tanjung Agung', 'Belimbing', 'Gunung Megang', 'Benakat', 'Ujan Mas', 'Rambang Niru', 'Lubai', 'Gelumbang'],
  'Kabupaten Lahat': ['Lahat', 'Merapi Barat', 'Merapi Timur', 'Merapi Selatan', 'Pulau Pinang', 'Kikim Barat', 'Kikim Timur', 'Jarai', 'Kota Agung', 'Tanjung Sakti'],
  'Kota Pekanbaru': ['Pekanbaru Kota', 'Sail', 'Sukajadi', 'Senapelan', 'Rumbai', 'Rumbai Barat', 'Rumbai Timur', 'Bukit Raya', 'Marpoyan Damai', 'Tenayan Raya', 'Kulim', 'Payung Sekaki', 'Tuah Madani', 'Bina Widya'],
  'Kota Makassar': ['Ujung Pandang', 'Makassar', 'Rappocini', 'Panakkukang', 'Bontoala', 'Wajo', 'Mariso', 'Mamajang', 'Tamalate', 'Tallo', 'Tamalanrea', 'Biringkanaya', 'Manggala', 'Kepulauan Sangkarrang'],
  'Kabupaten Luwu Timur': ['Malili', 'Nuha (Sorowako)', 'Wasuponda', 'Towuti', 'Mangkutana', 'Tomoni', 'Tomoni Timur', 'Kalaena', 'Wotu', 'Burau', 'Angkona'],
  'Kabupaten Morowali': ['Bungku Tengah', 'Bahodopi', 'Bungku Barat', 'Bungku Timur', 'Bungku Pesisir', 'Bungku Selatan', 'Menui Kepulauan', 'Witaponda', 'Bumi Raya'],
  'Kabupaten Mimika': ['Tembagapura', 'Kuala Kencana', 'Mimika Baru', 'Mimika Timur', 'Mimika Tengah', 'Mimika Barat', 'Agimuga', 'Jila', 'Jita'],
};

export const getDistrictsByCity = (cityName: string): string[] => {
  if (!cityName) return [];
  const cleanName = cityName.trim().toLowerCase();

  for (const [key, districts] of Object.entries(INDONESIA_DISTRICTS)) {
    const cleanKey = key.toLowerCase();
    if (
      cleanKey === cleanName ||
      cleanKey.replace(/^(kota|kabupaten)\s+/i, '') === cleanName.replace(/^(kota|kabupaten)\s+/i, '')
    ) {
      return districts;
    }
  }
  return [];
};

/**
 * Master Data Desa / Kelurahan per Kecamatan
 * Terhubung (inline cascading) dengan Kecamatan yang dipilih.
 */
export const INDONESIA_VILLAGES: Record<string, string[]> = {
  // KOTA BALIKPAPAN
  'Balikpapan Kota': ['Klandasan Ilir', 'Klandasan Ulu', 'Prapatan', 'Telaga Sari', 'Damai'],
  'Balikpapan Selatan': ['Sepinggan', 'Sepinggan Raya', 'Sepinggan Baru', 'Gunung Bahagia', 'Damai Baru', 'Damai Bahagia', 'Sungai Nangka'],
  'Balikpapan Utara': ['Gunung Samarinda', 'Gunung Samarinda Baru', 'Muara Rapak', 'Batu Ampar', 'Karang Joang', 'Graha Indah'],
  'Balikpapan Tengah': ['Gunung Sari Ilir', 'Gunung Sari Ulu', 'Karang Rejo', 'Karang Jati', 'Sumber Rejo', 'Mekar Sari'],
  'Balikpapan Barat': ['Baru Ilir', 'Baru Tengah', 'Baru Ulu', 'Margomulyo', 'Margo Mulyo', 'Kariangau'],
  'Balikpapan Timur': ['Manggar', 'Manggar Baru', 'Lamaru', 'Teritip'],

  // KOTA SAMARINDA
  'Samarinda Kota': ['Pasar Pagi', 'Pelabuhan', 'Karang Mumus', 'Sungai Pinang Luar', 'Bugis'],
  'Samarinda Ulu': ['Air Putih', 'Air Hitam', 'Dadi Mulya', 'Gunung Kelua', 'Jawa', 'Sidodadi', 'Teluk Lerong Ilir', 'Bukit Pinang'],
  'Samarinda Ilir': ['Selili', 'Sungai Dama', 'Sidomulyo', 'Sidodamai'],
  'Samarinda Seberang': ['Baqa', 'Gunung Panjang', 'Mangkupalas', 'Mesjid', 'Sungai Keledang'],
  'Sungai Kunjang': ['Loa Bakung', 'Loa Buah', 'Loa Bahu', 'Karang Asam Ilir', 'Karang Asam Ulu', 'Karang Anyar', 'Teluk Lerong Ulu'],
  'Palaran': ['Bukuan', 'Handil Bakti', 'Rawa Makmur', 'Bantuas', 'Simpang Pasir'],
  'Samarinda Utara': ['Sempaja Barat', 'Sempaja Timur', 'Sempaja Selatan', 'Sempaja Utara', 'Lempake', 'Sungai Siring', 'Budaya Pampang', 'Tanah Merah'],
  'Sungai Pinang': ['Bandara', 'Gunung Lingai', 'Mugirejo', 'Sungai Pinang Dalam', 'Temindung Permai'],
  'Sambutan': ['Sambutan', 'Sungai Kapih', 'Pulau Atas', 'Sindang Sari', 'Makroman'],
  'Loa Janan Ilir': ['Simpang Tiga', 'Tani Aman', 'Harapan Baru', 'Rapak Dalam', 'Sengkotek'],

  // KUTAI KARTANEGARA (KUKAR)
  'Tenggarong': ['Melayu', 'Panji', 'Sukirno', 'Timbau', 'Loa Ipuh', 'Loa Ipuh Darat', 'Loa Tebu', 'Mangkurawang', 'Maluhu', 'Bukit Biru', 'Jahab', 'Rapak Lambur', 'Bendang Raya'],
  'Tenggarong Seberang': ['Manunggal Jaya', 'Bangun Rejo', 'Buan Jaya', 'Karang Tunggal', 'Kerta Buana', 'Mulawarman', 'Perjiwa', 'Separi', 'Teluk Dalam'],
  'Loa Janan': ['Loa Duri Ilir', 'Loa Duri Ulu', 'Batuah', 'Purwajaya', 'Tani Bhakti', 'Bakungan', 'Tani Harapan'],
  'Loa Kulu': ['Loh Sumber', 'Ponoragan', 'Rempanga', 'Sepakat', 'Sumber Sari', 'Jembayan', 'Jembayan Tengah', 'Jembayan Dalam'],
  'Samboja': ['Kuala Samboja', 'Kampung Lama', 'Sanipah', 'Handil Baru', 'Tanjung Harapan', 'Teluk Pemedas', 'Ambarawang Darat', 'Ambarawang Laut', 'Salok Api Darat'],
  'Samboja Barat': ['Saloburo', 'Sungai Merdeka', 'Tani Bakti', 'Karya Merdeka', 'Bukit Raya'],
  'Muara Jawa': ['Muara Jawa Pesisir', 'Muara Jawa Ilir', 'Muara Jawa Ulu', 'Muara Jawa Tengah', 'Dondang', 'Teluk Dalam', 'Tama Pole'],
  'Anggana': ['Sungai Meriam', 'Anggana', 'Sidomulyo', 'Kutai Lama', 'Handil Terusan'],
  'Sangasanga': ['Jawa', 'Pendingin', 'Sangasanga Dalam', 'Sangasanga Muara', 'Sarijaya'],
  'Sebulu': ['Sebulu Modern', 'Sebulu Ilir', 'Sebulu Ulu', 'Beloro', 'Giri Agung', 'Manunggal Daya'],
  'Kota Bangun': ['Kota Bangun Ulu', 'Kota Bangun Ilir', 'Kota Bangun Seberang', 'Kedang Murung', 'Loleng', 'Liang'],
  'Muara Badak': ['Batu-Batu', 'Gas Alam Badak I', 'Muara Badak Ilir', 'Muara Badak Ulu', 'Saliki', 'Tanjung Limau'],
  'Marangkayu': ['Sebuntal', 'Batu Menyan', 'Makarti', 'Bunga Putih', 'Santan Tengah', 'Santan Ilir', 'Santan Ulu'],
  'Kembang Janggut': ['Kembang Janggut', 'Bukit Layang', 'Gentil', 'Loa Sakoh', 'Perdana', 'Pulau Pinang'],
  'Kenohan': ['Kahala', 'Tuana Tuha', 'Teluk Bingkai', 'Tubuhan'],
  'Tabang': ['Bila Talang', 'Gunung Sari', 'Kampung Baru', 'Ritan Baru', 'Tabang Lama'],

  // PENAJAM PASER UTARA (PPU / IKN NUSANTARA)
  'Penajam': ['Penajam', 'Nipah-Nipah', 'Gunung Seteleng', 'Sungai Parit', 'Nenang', 'Petung', 'Girimulyo', 'Salo Cella', 'Lawe-Lawe', 'Girimukti', 'Sotek', 'Sepapan'],
  'Sepaku': ['Sepaku', 'Maridan', 'Mentawir', 'Binuang', 'Semoi Dua', 'Sukamaju', 'Tengin Baru', 'Argo Mulyo', 'Bukit Raya', 'Pemaluan', 'Bumi Harapan'],
  'Waru': ['Waru', 'Sesulu', 'Api-Api', 'Bangun Mulya'],
  'Babulu': ['Babulu Darat', 'Babulu Laut', 'Gunung Mulia', 'Labangka', 'Rintik', 'Rawa Mulia', 'Sebakung Jaya'],

  // KUTAI TIMUR (KUTIM)
  'Sangatta Utara': ['Teluk Lingga', 'Singa Geweh', 'Swarga Bara', 'Sangatta Utara'],
  'Sangatta Selatan': ['Sangatta Selatan', 'Sangkima', 'Singa Gembara'],
  'Bengalun': ['Sepaso', 'Sepaso Barat', 'Sepaso Timur', 'Sepaso Selatan'],
  'Kaliorang': ['Bangun Jaya', 'Bukit Makmur', 'Bumi Sejahtera', 'Kaliorang', 'Selangkau'],
  'Muara Wahau': ['Muara Wahau', 'Nehas Liah Bing', 'Wasantah', 'Karya Bakti', 'Wahau Baru'],
  'Kongbeng': ['Miau Baru', 'Makmur Jaya', 'Sri Pantun', 'Sidomulyo'],
  'Rantau Pulung': ['Kebon Agung', 'Pulung Sari', 'Rantau Makmur', 'Tepian Makmur'],
  'Kaubun': ['Bumi Etam', 'Bumi Jaya', 'Bumi Rapak', 'Cipta Graha', 'Kadungan Jaya'],

  // KOTA BONTANG
  'Bontang Utara': ['Bontang Baru', 'Bontang Kuala', 'Guntung', 'Gunung Elai', 'Loktuan', 'Api-Api'],
  'Bontang Selatan': ['Berbas Pantai', 'Berbas Tengah', 'Bontang Lestari', 'Satimpo', 'Tanjung Laut', 'Tanjung Laut Indah'],
  'Bontang Barat': ['Belimbing', 'Kanaan', 'Gunung Telihan'],

  // KABUPATEN BERAU
  'Tanjung Redeb': ['Bugis', 'Gayam', 'Gunung Panjang', 'Karang Ambun', 'Sungai Bedungun', 'Tanjung Redeb'],
  'Sambaliung': ['Sambaliung', 'Batu-Batu', 'Pegat Bukur', 'Sei Bebanir Bangun', 'Rantau Panjang', 'Suaran', 'Tanjung Perangat'],
  'Gunung Tabur': ['Gunung Tabur', 'Maluang', 'Merancang Ilir', 'Merancang Ulu', 'Tasuk', 'Birang'],
  'Teluk Bayur': ['Teluk Bayur', 'Rinding', 'Tumbit Melayu', 'Labanan Jaya', 'Labanan Makmur'],

  // KABUPATEN PASER
  'Tanah Grogot': ['Tanah Grogot', 'Janju', 'Padang Pengrapat', 'Rantau Panjang', 'Sempalang', 'Tepian Batang', 'Senaken', 'Jone'],
  'Kuaro': ['Kuaro', 'Kendarom', 'Lolo', 'Modang', 'Padang Jaya', 'Pasir Mayang', 'Kerta Bumi'],
  'Batu Sopang': ['Songka', 'Batu Kajang', 'Kasungai', 'Rantau Buta', 'Rantau Layung', 'Sungai Terik'],

  // KOTA BANJARMASIN (KALSEL)
  'Banjarmasin Tengah': ['Antasan Besar', 'Gadang', 'Kertak Baru Ilir', 'Kertak Baru Ulu', 'Mawar', 'Melayu', 'Pasar Lama', 'Pekapuran Laut', 'Seberang Mesjid', 'Sungai Baru', 'Teluk Dalam'],
  'Banjarmasin Selatan': ['Basirih Selatan', 'Kelayan Barat', 'Kelayan Dalam', 'Kelayan Timur', 'Kelayan Tengah', 'Mantuil', 'Murung Raya', 'Pekauman', 'Pemurus Baru', 'Pemurus Dalam', 'Tanjung Pagar'],
  'Banjarmasin Timur': ['Benua Anyar', 'Karang Mekar', 'Kebun Bunga', 'Kuripan', 'Pekapuran Raya', 'Pengambangan', 'Sungai Bilu', 'Sungai Melayu'],
  'Banjarmasin Barat': ['Belitung Selatan', 'Belitung Utara', 'Kuin Cerucuk', 'Kuin Selatan', 'Pelambuan', 'Telaga Biru', 'Teluk Tiram'],
  'Banjarmasin Utara': ['Alalak Selatan', 'Alalak Tengah', 'Alalak Utara', 'Antasan Kecil Timur', 'Kuin Utara', 'Pangeran', 'Sungai Andai', 'Sungai Jingah', 'Sungai Miai'],

  // DKI JAKARTA
  'Gambir': ['Gambir', 'Kebon Kelapa', 'Petojo Utara', 'Duri Pulo', 'Cideng', 'Petojo Selatan'],
  'Tanah Abang': ['Bendungan Hilir', 'Karet Tengsin', 'Kebon Melati', 'Kebon Kacang', 'Kampung Bali', 'Petamburan', 'Gelora'],
  'Menteng': ['Menteng', 'Pegangsaan', 'Cikini', 'Gondangdia', 'Kebon Sirih'],
  'Setiabudi': ['Setiabudi', 'Karet', 'Karet Semanggi', 'Karet Kuningan', 'Kuningan Timur', 'Menteng Atas', 'Pasar Manggis', 'Guntur'],
  'Tebet': ['Tebet Barat', 'Tebet Timur', 'Kebon Baru', 'Bukit Duri', 'Manggarai', 'Manggarai Selatan', 'Menteng Dalam'],
  'Cilandak': ['Cilandak Barat', 'Cipete Selatan', 'Gandaria Selatan', 'Lebak Bulus', 'Pondok Labu'],
  'Kebayoran Baru': ['Selong', 'Gunung', 'Kramat Pela', 'Gandaria Utara', 'Cipete Utara', 'Pulo', 'Melawai', 'Petogogan', 'Rawa Barat', 'Senayan'],
  'Kebon Jeruk': ['Kebon Jeruk', 'Sukabumi Utara', 'Sukabumi Selatan', 'Kelapa Dua', 'Duri Kepa', 'Kedoya Selatan', 'Kedoya Utara'],
  'Kelapa Gading': ['Kelapa Gading Barat', 'Kelapa Gading Timur', 'Pegangsaan Dua'],

  // KOTA SURABAYA
  'Tegalsari': ['Tegalsari', 'Wonorejo', 'Dr. Soetomo', 'Kedungdoro', 'Keputran'],
  'Genteng': ['Genteng', 'Embong Kaliasin', 'Ketabang', 'Kapasari', 'Peneleh'],
  'Gubeng': ['Gubeng', 'Mojo', 'Airlangga', 'Baratajaya', 'Kertajaya', 'Pucangsewu'],
  'Wonokromo': ['Wonokromo', 'Darmo', 'Jagir', 'Ngagel', 'Ngagelrejo', 'Sawunggaling'],
  'Rungkut': ['Rungkut Kidul', 'Rungkut Menanggal', 'Kali Rungkut', 'Kedung Baruk', 'Medokan Ayu', 'Penjaringan Sari'],
};

export const getVillagesByDistrict = (districtName: string): string[] => {
  if (!districtName) return [];
  const cleanDistrict = districtName.trim().toLowerCase();

  for (const [key, villages] of Object.entries(INDONESIA_VILLAGES)) {
    const cleanKey = key.trim().toLowerCase();
    if (
      cleanKey === cleanDistrict ||
      cleanKey.replace(/^kecamatan\s+/i, '') === cleanDistrict.replace(/^kecamatan\s+/i, '')
    ) {
      return villages;
    }
  }
  return [];
};


