<?php

namespace App\Enums;

enum SecurityEventType: string
{
    case LOGIN_SUCCESS = 'LOGIN_SUCCESS';
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case ACCOUNT_LOCKED = 'ACCOUNT_LOCKED';
    case ACCOUNT_UNLOCKED = 'ACCOUNT_UNLOCKED';
    case PASSWORD_CHANGED = 'PASSWORD_CHANGED';
    case PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED';
    case PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED';
    case SESSION_REVOKED = 'SESSION_REVOKED';
    case MFA_ENABLED = 'MFA_ENABLED';
    case MFA_DISABLED = 'MFA_DISABLED';
}
